Let's create a new revision of the Software libraries
RobotPatient/Manikin_Software_Libraries pull request #28
Opened 2023-05-11 11:11 UTC by Hoog-V

The main branch seems to be stable enough now.. Let's try and merge it in to stable.. 

What has been added:
- Logger module with flash and serial possibilities
- Ringbuffer module made by @giopde1ste 
- Exception handling module

What has been changed:
- SPI slave has been refactored

2023-05-11 11:39 UTC, giopde1ste reviewed
I see now that we are missing quite a lot of doxygen documentation on most of the header files. maybe we should add this before pushing to stable?

2023-05-11 12:49 UTC, Hoog-V commented
Good idea! I'm gonna work on this too

2023-05-12 08:49 UTC, giopde1ste requested changes
We can discuss if my requested changes are actually needed in this pull request. But I do think it's worth thinking about what to document. Cause I don't think it's super useful to document a virtual function that has no default implementation. cause a new user that wants to use the interface doesn't wanna look at the base class of the class they are trying to use.

2023-05-12 08:49 UTC, giopde1ste commented on modules/hal_logger/src/hal_log_flash.hpp
> +  void init();
I understand why you didn't put any documentation here, but if you change the implementation of a virtual function you should still document it.

2023-05-12 08:49 UTC, giopde1ste commented on modules/hal_logger/src/hal_log_serial.hpp
> +  void writestr(const char* str);
Same with this, because you implement this function again. I think you should document this.

2023-05-12 08:49 UTC, giopde1ste commented on modules/hal_sensors/sensor_compression/src/sensor_compression.hpp
I am missing doxygen documentation here

2023-05-12 08:49 UTC, giopde1ste commented on modules/hal_exception/src/hal_exception_config.hpp
Maybe change this to the doxygen style?

2023-05-14 09:58 UTC, Hoog-V commented
All the files are documented now. I have not done the I2C as this will be changed soon. I also fixed several buffer overflow bugs/vulnerabilities.

2023-05-14 17:16 UTC, giopde1ste approved these changes
Great work man!

2023-05-14 17:38 UTC, merged